### PR TITLE
proper BS3 markup for navbar

### PR DESCRIPTION
**Pull request by Saboteur777**

### CODE REVIEW

**Comment by deviantony** [comment]
Thanks for the PR !

Could you describe what it brings? Also could you remove the `ui-for-docker-checksum.txt` file from the PR?

**Comment by Saboteur777** [comment]
Removed the file, as you requested, and attached an image about the layout. Not such a radical change, just a little bit cleaner. 
screencapture-localhost-9000-1473231119856

**Comment by deviantony** [comment]
I like the new layout. @kevana what do you think about it?

**Comment by kevana** [comment]
LGTM :shipit:

**Pull request merged**
