### PR TITLE
Patch angular-oboe to handle docker's JSON streams, such as events API

### PR DESCRIPTION
**Pull request by linquize**
Some docker APIs return JSON streams like below (`/events`)
```
{"status":"start","id":"54c17a09cd743b8c1ac4ff4ce3fe40fb3b703c844c07d1b17d4974d8478d245c","from":"dockerui/dockerui","time":1446223542}
{"status":"kill","id":"54c17a09cd743b8c1ac4ff4ce3fe40fb3b703c844c07d1b17d4974d8478d245c","from":"dockerui/dockerui","time":1446223545}
{"status":"die","id":"54c17a09cd743b8c1ac4ff4ce3fe40fb3b703c844c07d1b17d4974d8478d245c","from":"dockerui/dockerui","time":1446223545}
{"status":"stop","id":"54c17a09cd743b8c1ac4ff4ce3fe40fb3b703c844c07d1b17d4974d8478d245c","from":"dockerui/dockerui","time":1446223545}

```

So need to apply special patch for this.

### CODE REVIEW

**Comment by kevana** [comment]
How does this change the behavior of the events view? For image creation we added a response transformer that converted the series of JSON objects to a single object so Oboe could handle it, I'm not sure what the best approach is.

**Comment by deviantony** [comment]
This PR won't change anything to the Events view, I think?

I'm not even sure that Oboe is actually required, I did not found any possibility to stream events in the UI.

If there's no need for streaming capability, and thus we only need to poll events (current behaviour), then there's no need for Oboe. We could just create an EventFactory and use the response transformer used in the ImageFactory to have the exact same behaviour.

**Comment by deviantony** [comment]
Thanks for the PR but I'm closing this as it's outdated and not really required.

**Comment by linquize** [comment]
Btw is this problem gone?

**Comment by deviantony** [comment]
@linquize the question is: which problem?

**Comment by linquize** [comment]
Event:  2 json objects together without wrapped by a array.

**Comment by deviantony** [comment]
Yeah seems that there is no issue at the moment by using Oboe.

**Pull request closed without merging**
